export const videos = [
  {
    id: 1,
    name: "POCO X3 Pro Review: Should You Buy?",
    thumbnail: "https://i.ytimg.com/vi_webp/04VuzAppt48/mqdefault.webp",
    url: "04VuzAppt48",
    views: "675k",
    videoLength: "11:50",
  },
  {
    id: 2,
    name: "10 iPhone Settings You Should Change Right Now",
    thumbnail: "https://i.ytimg.com/vi_webp/Uj2Z4EohOvM/mqdefault.webp",
    url: "Uj2Z4EohOvM",
    views: "875k",
    videoLength: "07:40",
  },
  {
    id: 3,
    name: "ROG Phone 5: The Death Test!",
    thumbnail: "https://i.ytimg.com/vi_webp/zUXKzaOVb6Q/mqdefault.webp",
    url: "zUXKzaOVb6Q",
    views: "595k",
    videoLength: "07:35",
  },
  {
    id: 4,
    name: "OnePlus 9R Review: Should You Buy?",
    thumbnail: "https://i.ytimg.com/vi_webp/pLTUT4OR_BE/mqdefault.webp",
    url: "pLTUT4OR_BE",
    views: "525k",
    videoLength: "09:20",
  },
  {
    id: 5,
    name: "Realme 8 Pro First Impressions!",
    thumbnail: "https://i.ytimg.com/vi_webp/n4uxh5jq-1c/mqdefault.webp",
    url: "n4uxh5jq-1c",
    views: "895k",
    videoLength: "07:33",
  },
  {
    id: 6,
    name: "OnePlus Watch Review: Worth the Price?",
    thumbnail: "https://i.ytimg.com/vi/ZnZ5IuhhIIs/mqdefault.jpg",
    url: "ZnZ5IuhhIIs",
    views: "635k",
    videoLength: "09:51",
  },
  {
    id: 7,
    name: "The New Budget HP Chromebook!",
    thumbnail: "https://i.ytimg.com/vi_webp/iTPDRpbY5To/mqdefault.webp",
    url: "iTPDRpbY5To&t=51s",
    views: "845k",
    videoLength: "07:25",
  },
  {
    id: 8,
    name: "Realme Buds Air 2 Review: Buy or Not?",
    thumbnail: "https://i.ytimg.com/vi_webp/eQqyIwbXLEI/mqdefault.webp",
    url: "eQqyIwbXLEI",
    views: "1M",
    videoLength: "09:41",
  },
];
